FROM python:3.11-slim

WORKDIR /app

# Copiar dependencias
COPY requirements/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY . .

# Instalar el proyecto
RUN pip install -e .

# Exponer puerto
EXPOSE 8000

CMD ["uvicorn", "serving.app:app", "--host", "0.0.0.0", "--port", "8000"]